# .github/workflows/ci-cd.yml - CI/CD pipeline

name: CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Run tests
        run: pytest tests/
      - name: Run Bandit
        run: bandit -r src/
      - name: Run Safety
        run: safety check